Updating Challenge for Round 3
cityofcapetown/ds_code_challenge pull request #2
Opened 2022-06-08 20:24 UTC by Gordonei

## Overview
* Added section on "Things to focus on". Also added references to these attributes throughout the challenge
* Tweaked wording of (2) to suggest it's fine to just use H3 directly
* Changed question in (3) to focus on Water and Sanitation and Infrastructure.
* Adjusted wording of (4), and added anomaly detection challenge
* Adjusted wording of (5) to make clearer where we want judgement exercised.
* Removed (6) - we just weren't getting anything good back

2022-06-10 09:14 UTC, jolandabeck requested changes

2022-06-10 09:14 UTC, jolandabeck commented on README.md
> +1. An answer to the question "In which suburbs should Water and Sanitation concentrate their infrastructure improvement efforts?". Please motivate how you related the data provided to infrastructure
JB notes:  I suggest making the question more open ended.  My suggestion below, in my opinion, is a more advanced test for the candidate's ability to explore and derive value from a dataset that they are not familiar with.  

1. Identify value adding insights from the dataset provided with regards to electricity provision within the city.  
2. Develop a dashboard with visuals that draws the eye to performance pain points.  Add a note to each visual as to what business value it is adding in the context of the dashboard. (Extra credit for visuals that adapt automatically when a problem is addressed.  You may assume that new data will come in on a daily basis)

2022-06-10 15:48 UTC, ColinAnthony commented on README.md
> +3. *Classification challenge*: Classify a hex as sparsly or densely populated, solely based on the service request data. Provide an explantion as to how you're using the data to perform this classifi
We could ask them to expand on the classifications, highlighting any areas with unexpected classification and comment on why this may be the case

2022-06-10 16:00 UTC, ColinAnthony commented on README.md
> +2. *Introspection challenge*: Reshape the data into number of requests created, per type, per hex in the last 12 months. Chose a particular request type, or group of requests. Develop a model that pr
Might be worth slight re-phrasing
A) Reshape the data into number of requests created, per type, per hex in the last 12 months for a request type of your choice.
B) Develop a model that predicts the number of requests of your selected type
C) use this model to predict the number in A

2022-06-10 16:03 UTC, ColinAnthony commented on README.md
> +Please also remove any columns which you believe could lead to the resident who made the request being identified. We expect in the accompanying report that you will justify as to why this data is no
I would like a data engineering question where we give them some funny attributes tables and ask them to do a more complex join, possibly involving a groupby / window function or time bound or spatial join

2022-06-20 13:49 UTC, Gordonei commented on README.md
> +Please also remove any columns which you believe could lead to the resident who made the request being identified. We expect in the accompanying report that you will justify as to why this data is no
Mmm, ja, I like this idea - let's do some sort of temporal join. I thought maybe some rainfall data.

2022-06-20 14:22 UTC, Gordonei commented on README.md
> +1. An answer to the question "In which suburbs should Water and Sanitation concentrate their infrastructure improvement efforts?". Please motivate how you related the data provided to infrastructure
I'm going to incorporate your (2) into the existing (2) here, and add your (1) as a more open ended question (3). 

For (1), we're looking for a read on baseline level of data analytic competence - should be a straight-forward question, that can be executed competently in a reasonably short space of time. I like having something open ended on (3) to help test the time management - if they get stuck on (1) and (2), they won't do justice to (3).

2022-06-20 14:26 UTC, Gordonei commented on README.md
> +1. An answer to the question "In which suburbs should Water and Sanitation concentrate their infrastructure improvement efforts?". Please motivate how you related the data provided to infrastructure
Mmm, one point on (2) - I'm not going to include the programmatic element, as in the past we've found it has steered people to spend too much time on the tools, and not enough on the content

2022-06-21 20:22 UTC, Gordonei commented on README.md
> +Please also remove any columns which you believe could lead to the resident who made the request being identified. We expect in the accompanying report that you will justify as to why this data is no
I found some nice wind speed data, so I've included a spatial filter issue (select requests around a specific point), and then a temporal join.

As  a bonus, the wind data is structured as a human readable spreadsheet, so there will be some data munging to get something sensible out.

2022-06-21 20:31 UTC, Gordonei commented on README.md
> +2. *Introspection challenge*: Reshape the data into number of requests created, per type, per hex in the last 12 months. Chose a particular request type, or group of requests. Develop a model that pr
Done - I've itemised the list as per your comment, as I think it's clearer

2022-06-22 15:36 UTC, ColinAnthony commented on README.md
> +2. Augment your filtered subsample of `sr_hex.csv.gz` from (1) with the appropriate [wind direction and speed data for 2020](https://www.capetown.gov.za/_layouts/OpenDataPortalHandler/DownloadHandler
the link here doesn't work for me.

should be virtually identical (`%3F to %2F`):

https://www.capetown.gov.za/_layouts/OpenDataPortalHandler/DownloadHandler.ashx?DocumentName=Wind_direction_and_speed_2020.ods&DatasetDocument=https%3A%2F%2Fcityapps.capetown.gov.za%2Fsites%2Fopendatacatalog%2FDocuments%2FWind%2FWind_direction_and_speed_2020.ods

but the website is nuts... out of date links and text claiming to be links, but just static text :(

2022-06-22 15:39 UTC, ColinAnthony commented
Happy to merge with the fixed link!

2022-06-22 18:18 UTC, merged